info:
  namespace: rpghuds
huds:
  money:
    enabled: true
    show:
      auto: false
      underwater: false
    type: CUSTOM
  stars:
    enabled: true
    show:
      auto: false
      underwater: false
    type: CUSTOM